### ISSUE TITLE
pileup command error libpileup_lib.so missing

### ISSUE THREAD

**Issue by LuLexiLiu** [ratschlab/secedo#18]
Hi Daniel,

I installed secedo v1.0.4 by conda install -c conda-forge -c bioconda secedo on a linux cluster, everything was fine. However, when I tried to call the pileup command, an error occurred saying 'pileup: error while loading shared libraries: libpileup_lib.so: cannot open shared object file: No such file or directory'. Any ideas? Thanks.

**Comment by danieldanciu** [comment]
Problem fixed, a new conda install should be available within a few hours.

**Comment by danieldanciu** [comment]
Marking this as resolved, please reopen if you are still facing issues.

**Comment by LuLexiLiu** [comment]
Thank you Daniel for the quick response! The problem is solved.
